// svelte/src/routes/(auth)/login/+page.svelte
<script lang='ts'>
	import LoginInput from "../../../components/LoginInput.svelte";

    var form: HTMLFormElement;
    var error = false;
    var errorMessage = '';

    interface Form {
        nickname: string
        email: string
        password: string
    }

    async function handleSubmit(e: Event) {
        let data: Form = Object.fromEntries(new FormData(form)) as unknown as Form
        await fetch(
            '/auth/login',
            {
                method: 'POST',
                body: JSON.stringify(data),
                headers: {
                    'Content-Type': 'application/json'
                }
            }
        ).then((res) => {
            if (res.ok && res.redirected) {
                window.location.assign(res.url)
                return
            }

            error = true
            errorMessage = res.status === 401 ?
                           'Неверный логин или пароль' : 
                           'Произошла ошибка, попробуйте позже!'
        })
    }

</script>

<svelte:head>
    <title>Book и друг | Вход</title>
</svelte:head>

<div class='fixed w-full h-full bg-gray-200'>
    <div class='flex
                md:w-1/2 sm:w-full h-full bg-white
                items-center justify-center
                shadow-2xl'>
        <form class='flex flex-col w-[70%]' on:submit|preventDefault={handleSubmit} bind:this={form}>
            <LoginInput label='Никнейм' type='text' id='nickname' 
                        pattern="^[^0-9][a-zA-Z0-9]{'{4,}'}$" 
                        errorMsg='Никнейм должен содержать не менее 5 латинских букв и цифр'
            />
            <LoginInput label='Пароль' type='password' id='password' 
                        pattern="^(?=.*[0-9])(?=.*[!_@#$%^&*])[a-zA-Z0-9!_@#$%^&*]{'{6,16}'}$"
                        errorMsg='Пароль должен быть не короче 6 символов и состоять из латинского алфавита, цирф и спецсимволов'
            />

            {#if error}
                <span class='text-red-500 text-xl text-center mt-16'>{errorMessage}</span>
            {/if}

            <button type='submit' class='bg-red-400 rounded-xl w-full h-12 font-semibold {error && 'mt-20'} mt-32'>Войти</button>
            <span class='mt-2 ml-3'>
                Ещё нет аккаунта? 
                <a href='/register' class='text-blue-800'>Присоединиться</a>
            </span>
        </form> 
    </div>
</div>

// frontend/src/pages/Login.tsx
import { Link } from "@solidjs/router";
import Visibility from "@suid/icons-material/Visibility";
import VisibilityOff from "@suid/icons-material/VisibilityOff";
import { Box, Button, Container, FormControl, IconButton, Input, InputLabel, Typography } from "@suid/material";
import { Component, createSignal, onMount } from "solid-js";

const Login: Component = () => {
    const [showPwd, setShowPwd] = createSignal(false)
    const [headerError, setHeaderError] = createSignal({
        status: false,
        message: ''
    })
    const [formData, updateForm] = createSignal({
        login: null, 
        password: null
    })

    function onSubmit(event: Event) {
        event.preventDefault()
        
        fetch(
            '/auth/login',
            {
                method: 'POST',
                body: JSON.stringify(formData()),
                headers: {
                    'Content-Type': 'application/json'
                }
            }
        ).then(response => {
            if (response.status === 401) {
                setHeaderError({
                    status: true,
                    message: 'Неверный логин или пароль.'
                })
                return
            }
            if (response.status !== 200) {
                setHeaderError({
                    status: true, 
                    message: 'Произошла ошибка, попробуйте позже.'
                })
                return
            }

            if (response.redirected) {
                window.location.assign(response.url)
            }
        })
        .catch((_) => {
            setHeaderError({
                status: true, 
                message: 'Произошла ошибка, попробуйте позже.'
            })
            return
        })
    }

    function onChange(event: Event) {
        updateForm({
          ...formData(),
          [(event.target as HTMLElement).id]: (event.target as HTMLTextAreaElement).value
        })
    }

    onMount(() => {
        document.title = 'Book и друг | Авторизация'
    })

    return (
        <Box sx={{
            width: '100vw',
            height: '100vh',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center'
        }}>
            <Container sx={{
                display: 'flex',
                flexDirection: 'column',
                width: '400px',
                justifyContent: 'center',
                alignItems: 'center',
                boxShadow: '#00000029 0 0 25px',
                padding: '25px',
                borderRadius: '8px',
            }}>
                <Typography sx={{
                    fontSize: '22px',
                    width: '100%',
                    textAlign: 'center'
                }}>
                    Вход
                </Typography>
                {headerError().status && <Typography sx={{color: '#d32f2f', textAlign: 'center'}}>{headerError().message}</Typography>}
                <form 
                    onSubmit={onSubmit}
                    style='width: 90%'
                >
                    <FormControl 
                        fullWidth 
                        sx={{
                            mt: '15px'
                    }}>
                        <InputLabel for='login'>Логин</InputLabel>
                        <Input id='login' onChange={onChange}/>
                    </FormControl>
                    <FormControl 
                        fullWidth 
                        sx={{
                            display: 'flex',
                            flexDirection: 'row',
                            alignItems: 'end',
                            mt: '15px'
                    }}>
                        <InputLabel for='password'>Пароль</InputLabel>
                        <Input fullWidth id='password' type={showPwd() ? 'text' : 'password'} onChange={onChange}/>
                        <IconButton
                            onClick={() => setShowPwd(!showPwd())}
                            children={showPwd() ?  <VisibilityOff/> : <Visibility/>}
                            size='large'
                            sx={{
                                ml: '5px',
                                width: '25px', 
                                height: '25px'
                            }}
                        />
                    </FormControl>
                    <Button fullWidth type='submit' sx={{mt: '10px'}}>Войти</Button>
                </form>
                <Typography>Ещё нет аккаунта? <Link href='/register' children={'Создать'}/></Typography>
            </Container>
        </Box>
    )
}

export default Login;
