// svelte/src/routes/(auth)/register/+page.svelte
<script lang='ts'>
	import RepeatPwd from "../../../components/RepeatPwd.svelte";
    import LoginInput from "../../../components/LoginInput.svelte";

    var pwdNotEqual = false;
    var form: HTMLFormElement;
    
    var error = false;
    var errorMessage = '';

    interface Form {
        nickname: string
        email: string
        password: string
        repeat: string
    }

    async function handleSubmit(e: Event) {
        if (pwdNotEqual) return;
        let data: Form = Object.fromEntries(new FormData(form)) as unknown as Form
        await fetch(
            '/auth/register',
            {
                method: 'POST',
                body: JSON.stringify(data),
                headers: {
                    'Content-Type': 'application/json'
                }
            }
        ).then((res) => {
            if (res.ok && res.redirected) {
                window.location.assign(res.url)
                return
            }

            error = true
            errorMessage = res.status === 409 ?
                           'Пользователь с таким именем уже существует!' : 
                           'Произошла ошибка, попробуйте позже!'
        })
    }

    function validateRepeat() {
        let data: Form = Object.fromEntries(new FormData(form)) as unknown as Form
        console.log(data);
        pwdNotEqual = data.password !== data.repeat
    }
</script>

<svelte:head>
    <title>Book и друг | Регистрация</title>
</svelte:head>

<div class='fixed w-full h-full bg-gray-200'>
    <div class='flex
                md:w-1/2 sm:w-full h-full bg-white
                items-center justify-center
                shadow-2xl'>
        <form class='flex flex-col w-[70%]' on:submit|preventDefault={handleSubmit} bind:this={form}>
            <LoginInput label='Никнейм' type='text' id='nickname' 
                        pattern="^[^0-9][a-zA-Z0-9]{'{4,}'}$"
                        errorMsg='Никнейм должен содержать не менее 5 латинских букв и цифр'
            />
            <LoginInput label='Email' type='email' id='email'
                        pattern='^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{'{2,3}'})+$'
                        errorMsg='Неверный Email'
            />
            <LoginInput label='Пароль' type='password' id='password'
                        pattern="^(?=.*[0-9])(?=.*[!_@#$%^&*])[a-zA-Z0-9!_@#$%^&*]{'{6,16}'}$"
                        errorMsg='Пароль должен быть не короче 6 символов и состоять из латинского алфавита, цифр и спецсимволов'
            />
            <RepeatPwd label='Повторите пароль' type='password' id='repeat'
                       pattern="^(?=.*[0-9])(?=.*[!_@#$%^&*])[a-zA-Z0-9!_@#$%^&*]{'{6,16}'}$"
                       errorMsg='Невалидный пароль'
                       pwdNotEqual={pwdNotEqual}
                       on_change={validateRepeat}
            />
            
            {#if error}
                <span class='text-red-500 text-xl text-center mt-16'>{errorMessage}</span>
            {/if}

            <button type='submit' class='bg-red-400 rounded-xl w-full h-12 font-semibold {error && 'mt-20'} mt-32'>Присоединиться</button>
            <span class='mt-2 ml-3'>
                Уже есть аккаунт? 
                <a href='/login' class='text-blue-800'>Войти</a>
            </span>
        </form> 
    </div>
</div>

// frontend/src/pages/Register.tsx
import { Link } from "@solidjs/router";
import Visibility from "@suid/icons-material/Visibility";
import VisibilityOff from "@suid/icons-material/VisibilityOff";
import { Box, Button, Container, FormControl, FormHelperText, IconButton, Input, InputLabel, Typography } from "@suid/material"
import { Component, createSignal, onMount } from "solid-js";

const Register: Component = () => {
    const [showPwd, setShowPwd] = createSignal(false)
    const [pwdsError, setPwdsError] = createSignal(false)
    const [headerError, setHeaderError] = createSignal({
        status: false,
        message: ''
    })

    const [formData, updateForm] = createSignal({
        nickname: null,
        password: null,
        password_repeat: null,
    })

    function onChange(event: Event) {
        updateForm({
          ...formData(),
          [(event.target as HTMLElement).id]: (event.target as HTMLTextAreaElement).value
        })
    }

    function submit(event: SubmitEvent) {
        event.preventDefault()
        
        if (formData().password !== formData().password_repeat) {
            setPwdsError(true)
            return
        }

        const data = formData()
        const modifiedData = {
            nickname: data.nickname,
            password: data.password
        }        

        fetch(
            '/auth/register',
            {
                method: 'POST',
                body: JSON.stringify(modifiedData),
                headers: {
                    'Content-Type': 'application/json'
                }
            }
        ).then((response) => {
            if (response.status === 409) {
                setHeaderError({
                    status: true, 
                    message: 'Пользователь с этим логином уже существует!'
                })
                return
            } 
            if (response.status !== 200) {
                setHeaderError({
                    status: true, 
                    message: 'Произошла ошибка, попробуйте позже.'
                })
                return
            }
            
            if (response.redirected) {
                window.location.assign(response.url)
            }
        })
        .catch((_) => {
            setHeaderError({
                status: true, 
                message: 'Произошла ошибка, попробуйте позже.'
            })
            return
        })
    }

    onMount(() => {
        document.title = 'Book и друг | Регистрация'
    })

    return (
        <Box sx={{
            width: '100vw',
            height: '100vh',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center'
        }}>
            <Container sx={{
                display: 'flex',
                flexDirection: 'column',
                width: '400px',
                justifyContent: 'center',
                alignItems: 'center',
                boxShadow: '#00000029 0 0 25px',
                padding: '25px',
                borderRadius: '8px',
            }}>
                <Typography sx={{
                    fontSize: '22px',
                    width: '100%',
                    textAlign: 'center'
                }}>
                    Регистрация
                </Typography>
                {headerError().status && <Typography sx={{color: '#d32f2f', textAlign: 'center'}}>{headerError().message}</Typography>}
                <form 
                    onSubmit={submit}
                    style='width: 90%'
                >
                    <FormControl 
                        fullWidth 
                        sx={{
                            mt: '15px'
                    }}>
                        <InputLabel for='login' required>Логин</InputLabel>
                        <Input id='login' required onChange={onChange}/>
                    </FormControl>
                    <FormControl 
                        fullWidth 
                        sx={{
                            display: 'flex',
                            flexDirection: 'row',
                            alignItems: 'end',
                            mt: '15px'
                    }}>
                        <InputLabel for='password' required>Пароль</InputLabel>
                        <Input fullWidth id='password' type={showPwd() ? 'text' : 'password'} required onChange={onChange}/>
                        <IconButton
                            onClick={() => setShowPwd(!showPwd())}
                            children={showPwd() ?  <VisibilityOff/> : <Visibility/>}
                            size='large'
                            sx={{
                                ml: '5px',
                                width: '25px', 
                                height: '25px'
                            }}
                        />
                    </FormControl>
                    <FormControl 
                        fullWidth 
                        sx={{
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'end',
                            mt: '15px'
                    }}>
                        <InputLabel for='password_repeat' required>Подтверждение</InputLabel>
                        <Input 
                            fullWidth 
                            id='password_repeat' 
                            type='password' 
                            required 
                            onChange={(event) => {onChange(event); setPwdsError(false)}}/>
                        {pwdsError() && <FormHelperText error>Пароли не совпадают</FormHelperText>}
                    </FormControl>
                    <Button fullWidth type='submit' sx={{mt: '10px'}}>Зарегистрироваться</Button>
                </form>
                <Typography sx={{
                    mt: '5px'
                }}>
                    Уже есть аккаунт? 
                    <Link href='/login' children={'Войти'}/>
                </Typography>
            </Container>
        </Box>
    )
}

export default Register
